### ISSUE TITLE
Did you see different behavior when used in different files?

### ISSUE THREAD

**Issue by saltycrane** [pcardune/flowtype-hoc-exploration#2]
Thanks for your notes-- they were really informative for me!

Did you notice different Flow behavior when the code is in different files?

When the code is all in 1 file (Profile.js) here: https://github.com/saltycrane/flowtype-hoc-exploration/tree/fc09e5f3a0eb62d500c31d996a16610ab682f8e1

I get 2 errors as expected:

```
    $ npm run -s flow
    Profile.js:25
     25:   <LoggedProfile
           ^ React element `LoggedProfile`
     26:     username={1234}
                       ^^^^ number. This type is incompatible with
      6: function Profile(props:{username:string, onEdit:Function}) {
                                          ^^^^^^ string

    Profile.js:25
     25:   <LoggedProfile
           ^ React element `LoggedProfile`
     27:     onEdit={"not implemented yet"}
                     ^^^^^^^^^^^^^^^^^^^^^ string. This type is incompatible with
      6: function Profile(props:{username:string, onEdit:Function}) {
                                                         ^^^^^^^^ function type


    Found 2 errors
```

Then I modified the code into 2 files (App.js and Profile.js) here: https://github.com/saltycrane/flowtype-hoc-exploration/tree/4e3150217dc62ef960a8b4e80680bee772a14307

And I got this unexpected error:

```
    $ npm run -s flow
    Profile.js:22
     22: const LoggedProfile = logOnRender(Profile);
                               ^^^^^^^^^^^^^^^^^^^^ type parameter `FirstOrderProps` of function call. Missing annotation


    Found 1 error
```

Then I separated the code into 3 files (App.js, Profile.js and logOnRender.js) here: https://github.com/saltycrane/flowtype-hoc-exploration/tree/b56850c3cbf95cd9702f3e6fd53adcc4d8e760bc

And I got 0 errors which is not expected:

```
    $ npm run -s flow
    No errors!
```

Just wondering if you have seen this. I am using Flow 0.33.0 and Node v6.4.0.

**Comment by pcardune** [comment]
that sounds fishy. I have not tried this, but I did notice some problems with 0.33.0 that don't seem to show up in 0.32. Have you tried with an older version of flow?

**Comment by saltycrane** [comment]
Thanks for your response.

I tried 0.32.0 and 0.31.1 also and got the same results.

I found someone else ran into this issue here: https://github.com/facebook/flow/issues/2541

I will try to dig into that issue some more.

**Comment by saltycrane** [comment]
I added a summary of my findings here: https://github.com/saltycrane/flowtype-hoc-exploration/blob/notes/README.md

I solved the issue by explicitly declaring the type of the exported wrapped component. But I think it is a Flow bug that Flow does not require you to do this and reports 0 errors when there should be 2.

**Comment by rodrigopr** [comment]
Great idea with the repo/notes, might help lot of people.

I've done some investigation in flow code, but couldn't find the root of the issue.
I also found another workaround, definitely not perfect, but I think it can be less verbose than alternatives.

If we define a union type:

``` jsx
export type ClassComponent<D, A, S> = Class<React$Component<D, A, S>>;
export type FunctionComponent<P> = (props: P) => ?React$Element<any>;
export type StatelessComponent<A> = FunctionComponent<A> | ClassComponent<void, A, void>;
```

Using `StatelessComponent` in the HOC:

``` jsx
function logOnRender<P>(FirstOrderComponent: StatelessComponent<P>): StatelessComponent<FirstOrderProps> {
  return function NewComponent(firstOrderProps: FirstOrderProps) {
    console.log("Rendering with props:", firstOrderProps);
    return <FirstOrderComponent {...firstOrderProps}/>;
  }
}
```

And explicit tell the type only of the component using arrow function:

``` jsx
type ProfileProps = { username:string, onEdit:Function };

const Profile: StatelessComponent<ProfileProps> = (props) => (
  <div>
    Your Username: {props.username}
    <button onClick={props.onEdit}>Edit Profile</button>
  </div>
);

export default logOnRender(Profile);
```

Don't work using `FunctionComponent` directly in `const Profile: FunctionComponent<ProfileProps>`.

I think this work best with arrow function. But for `function Profile(props) {}` style I guess you could typecast on `logOnRender((Profile: Component<ProfileProps>))`

**Comment by saltycrane** [comment]
Rodrigo, thanks for your tips.

I think I have enough working to meet my needs at the moment. My updates are in this branch: https://github.com/saltycrane/flowtype-hoc-exploration/tree/folders

I got stuck on a couple things: flow typing the subtractive HOC and using the unionized type with a class based component. To get around #1, I'm just declaring the type of the wrapped component returned by the HOC without typing the actual HOC. This meets my needs because I'm doing this for an external library anyways (react-with-styles). To get around #2, I will use 2 types (functional and classy) instead of 1 that covers both.
